
PORT = 8020
SERVER_IP = "0.0.0.0"
BIND = (SERVER_IP, PORT)
CHUNK_SIZE = 1024
FILE_NOT_FOUND = "NOFILE"
END_THE_PROGRAM = "DONE"
EMPTY_FILE= "Empty file"
MAGIC_END_FILE_KEY = b"$$$<--<@>--->$$$"
OUTPUT_DIR_NAME = "output"